// src/art.js — pre-generated halftone ASCII art: a sagittal limbic-brain cutaway.
// Rendered from an anatomical SVG (cingulate, corpus callosum, thalamus, amygdala,
// hippocampus, cerebellum, brainstem) via luminance->char-density mapping with
// Floyd-Steinberg dithering. Terminal variants (charAspect ~2.05 = a terminal cell).
// Stored as base64 so ramp chars survive. Decode: Buffer (Node) / atob (browser).

export const ART_B64 = {
  hero: "ICAgICAgIDppX1tbW3sxfTEpMVt9MTF7PytsXi4KICAgICExMSkxKH0ofH0xKTEpfCgpKDEoMTF9MX0/WytJCiAgXn17MSgpfFxZMFFDMDBPTExRQ0NMQ0xKWWYxW1tdXV0/XgogbHt7KTExendrZGtNJSQkJCQkJCQlJm9iWkNYVVFVMT8tPy0tCkl9MXt7KXAjJSQkYW1MWHpubnhyai9mam52WUxDanxMMV8/P35pCi1dWzEpeiQkJDBuUXBRVTBMQ2N4XHwpfTEpKX0xW10tXVs/fml+Ci1dXT9ddGhvQ3J3Qykod2RkZGRkWHsxKTF9XX1bfVstXS0tX2kKSV1dW31bfXtdWyhVWSlmd00jbXp8MVtdfVtfP1stXystaWwuCiBgfistPy0/LT9VJCRwIyQkJGtqXS0/LS0tPz8/Py0tW3t7e31+CiAgICAnaV9fKysrLS0/W3Ulei1fLStffkkgJygoKDExMTExMTF7MV4KICAgICAgICAgICAgICAgICAgICAgICAgICAgfSgoKTExKTEpMTExJwogICAgICAgICAgICAgICAgICAgICAgICAgICAuKCgxfl17MX0/bAogICAgICAgICAgICAgICAgICAgICAgICAgICAgISgoCiAgICAgICAgICAgICAgICAgICAgICAgICAgICAgbEku",
  cli: "ICAgICAgIDppX1tbW3sxfTEpMVt9MTF7PytsXi4KICAgICExMSkxKH0ofH0xKTEpfCgpKDEoMTF9MX0/WytJCiAgXn17MSgpfFxZMFFDMDBPTExRQ0NMQ0xKWWYxW1tdXV0/XgogbHt7KTExendrZGtNJSQkJCQkJCQlJm9iWkNYVVFVMT8tPy0tCkl9MXt7KXAjJSQkYW1MWHpubnhyai9mam52WUxDanxMMV8/P35pCi1dWzEpeiQkJDBuUXBRVTBMQ2N4XHwpfTEpKX0xW10tXVs/fml+Ci1dXT9ddGhvQ3J3Qykod2RkZGRkWHsxKTF9XX1bfVstXS0tX2kKSV1dW31bfXtdWyhVWSlmd00jbXp8MVtdfVtfP1stXystaWwuCiBgfistPy0/LT9VJCRwIyQkJGtqXS0/LS0tPz8/Py0tW3t7e31+CiAgICAnaV9fKysrLS0/W3Ulei1fLStffkkgJygoKDExMTExMTF7MV4KICAgICAgICAgICAgICAgICAgICAgICAgICAgfSgoKTExKTEpMTExJwogICAgICAgICAgICAgICAgICAgICAgICAgICAuKCgxfl17MX0/bAogICAgICAgICAgICAgICAgICAgICAgICAgICAgISgoCiAgICAgICAgICAgICAgICAgICAgICAgICAgICAgbEku",
  mini: "ICAgICAuIjpJISsrISFsXi4KICAiMVwvXGpyY1hZWFhuZnwoe10hCiAtXC94bW8lQCRAJSUmJk1rQ0p4fXstCl98XHYkJDhoa1pKenZycnVYVXhuKHtdfgpbezF6JVpaWnhoTSNiXFxcMSgpfXtbLScKJ1t7MTF7dSRxYSQlcil7e317fT97XSEuCiAgIEl+fmlfW3JoXF9pbCIudC9cXC9cXF0KICAgICAgICAgICAgICAgICA/ZjEpXCg/CiAgICAgICAgICAgICAgICAgIHxd",
};
const dec=(b)=>typeof Buffer!=="undefined"?Buffer.from(b,"base64").toString("utf8"):decodeURIComponent(escape(atob(b)));
export const BRAIN_HERO=dec(ART_B64.hero);
export const BRAIN_CLI=dec(ART_B64.cli);
export const BRAIN_MINI=dec(ART_B64.mini);
